function [y,n] = sigmult(x1,n1,x2,n2)
figure;
subplot(2,2,1);
stem(n1,x1);
title('The first signal');
xlabel('n1');
ylabel('x1(n1)');
subplot(2,2,2);
stem(n2,x2);
title('The second signal');
xlabel('n2');
ylabel('x2(n2)');
n = min(min(n1),min(n2)):max(max(n1),max(n2));
y1=zeros(1,length(n));
y2=y1;
y1(find((n>=min(n1))&(n<=max(n1))))=x1;
y2(find((n>=min(n2))&(n<=max(n2))))=x2;
y= y1.* y2;
subplot(2,2,[3 4]);
stem(n,y);
title('multiplication of two signals');
xlabel('n');
ylabel('y(n)');